version: '2'

services:
  cassandra:
    image: cassandra:3
    container_name: cassandra-database

  kong:
    image: kong:0.10.3
    # Cassandra takes a while to initialize so Kong will error out, ensure it restarts so that when Cassandra is ready
    # then Kong will also be up and ready to take requests
    restart: always
    container_name: kong-api-gateway
    # make use of the container-name DNS to reference the database
    environment:
      - "KONG_DATABASE=cassandra"
      - "KONG_CASSANDRA_CONTACT_POINTS=cassandra-database"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
    depends_on:
      - "cassandra"
